---
- name: Install Multiple
  hosts: all
    #become: true
  tasks:
  - name: Install a package
    yum:
      name: httpd
      state: installed
  - name: Start a service
    service: 
      name: httpd
      state: started

...

