---
- name: Creating a user using variable
  hosts: all
  become: true

  vars_files:
    - test_file.yml 
     

  tasks:
  - name: Creates a {{username}}
    user: 
      name: "{{username}}"

...           
